manifest:
  remotes:
  - name: nxp
    url-base: https://github.com/NXP
  - name: nxp-zephyr
    url-base: https://github.com/nxp-zephyr
  - name: nxp-mcuxpresso
    url-base: https://github.com/nxp-mcuxpresso
  defaults:
    remote: nxp-mcuxpresso
  projects:
  - name: bifrost
    path: bifrost
    remote: nxp-zephyr
    revision: 9d7384cbecd58e98a32db5033d1d212202fe00d9
    west-commands: scripts/west_commands.yml
    groups:
    - bifrost
    userdata:
      track_branch: main
  - name: core
    path: mcuxsdk/
    repo-path: mcuxsdk-core
    revision: 4683ac1bd05d307bd2fe7abc0a6d1fabd87d2ad1
    west-commands: scripts/west_commands.yml
    groups:
    - core
    userdata:
      track_branch: release/24.12.00
  - name: CMSIS
    repo-path: mcu-sdk-cmsis
    path: mcuxsdk/arch/arm/CMSIS
    revision: c3319a16588d05036a9e08cf59a92634a5a0e5dd
    groups:
    - core
    userdata:
      track_branch: release/24.12.00
  - name: mcux-soc-svd
    path: mcuxsdk/svd
    revision: main
    groups:
    - optional
    userdata:
      track_branch: main
  - name: mcu-sdk-examples
    revision: 5db14ac9e5261510a3c693fedc785f0c3225bd5c
    repo-path: mcuxsdk-examples
    path: mcuxsdk/examples
    groups:
    - examples
    userdata:
      track_branch: release/24.12.00
  - name: mcu-sdk-components
    repo-path: mcux-component
    revision: bf0417a1af0d5a908f8781f82ae4a4a7d675cc6c
    path: mcuxsdk/components
    groups:
    - components
    userdata:
      track_branch: release/24.12.00
  - name: mcu-sdk-doc
    repo-path: mcuxsdk-doc
    revision: 929ca6d84bdd777a41dd7b23e7070cf36533b99f
    path: mcuxsdk/docs
    west-commands: scripts/west_commands.yml
    groups:
    - doc
    userdata:
      track_branch: release/24.12.00
  - name: mcuxsdk-tool-data
    revision: 847bb0d79805065d45b5e6aa57e3d8d7a0ac7d48
    path: mcuxsdk/tool_data
    groups:
    - core
    userdata:
      track_branch: release/24.12.00
