manifest:
  remotes:
  - name: nxp
    url-base: https://github.com/NXP
  - name: nxp-zephyr
    url-base: https://github.com/nxp-zephyr
  - name: nxp-mcuxpresso
    url-base: https://github.com/nxp-mcuxpresso
  defaults:
    remote: nxp-mcuxpresso
  projects:
  - name: bifrost
    path: bifrost
    remote: nxp-zephyr
    revision: main
    west-commands: scripts/west_commands.yml
    groups:
    - bifrost
    userdata:
      track_branch: main
  - name: core
    path: mcuxsdk/
    repo-path: mcuxsdk-core
    revision: 071130e031d0705a29d0dd65df98abdd7509523d
    west-commands: scripts/west_commands.yml
    groups:
    - core
    - ble_nxp
    userdata:
      track_branch: main
  - name: CMSIS
    repo-path: mcu-sdk-cmsis
    path: mcuxsdk/arch/arm/CMSIS
    revision: c3319a16588d05036a9e08cf59a92634a5a0e5dd
    groups:
    - core
    - ble_nxp
    userdata:
      track_branch: mcux_main
  - name: mcux-soc-svd
    path: mcuxsdk/svd
    revision: main
    groups:
    - optional
    userdata:
      track_branch: main
  - name: mcu-sdk-examples
    revision: 8e79a4a942f73c83b8335e494cbd17c35f20d8ec
    repo-path: mcuxsdk-examples
    path: mcuxsdk/examples
    groups:
    - examples
    - ble_nxp
    userdata:
      track_branch: main
  - name: mcu-sdk-components
    repo-path: mcux-component
    revision: f8ee4efce5be95ff39a1890faadb93d0786c6ac3
    path: mcuxsdk/components
    groups:
    - components
    - ble_nxp
    userdata:
      track_branch: mcux_main
  - name: mcu-sdk-doc
    repo-path: mcuxsdk-doc
    revision: 0547ac7f9fffd1820ffbac40e8244e1333f8ba1f
    path: mcuxsdk/docs
    west-commands: scripts/west_commands.yml
    groups:
    - doc
    userdata:
      track_branch: main
  - name: mcuxsdk-tool-data
    revision: d4e6ad4f43a6b260fb26a1e56c469891a63c01a9
    path: mcuxsdk/tool_data
    groups:
    - core
    userdata:
      track_branch: main
