manifest:
  remotes:
  - name: nxp
    url-base: https://github.com/NXP
  - name: nxp-zephyr
    url-base: https://github.com/nxp-zephyr
  - name: nxp-mcuxpresso
    url-base: https://github.com/nxp-mcuxpresso
  defaults:
    remote: nxp-mcuxpresso
  projects:
  - name: bifrost
    path: bifrost
    remote: nxp-zephyr
    revision: main
    west-commands: scripts/west_commands.yml
    groups:
    - bifrost
    userdata:
      track_branch: main
  - name: core
    path: mcuxsdk/
    repo-path: mcuxsdk-core
    revision: 49f455cb6edfb8f00cf4e82643d00397b527c234
    west-commands: scripts/west_commands.yml
    groups:
    - core
    - ble_nxp
    userdata:
      track_branch: main
  - name: CMSIS
    repo-path: mcu-sdk-cmsis
    path: mcuxsdk/arch/arm/CMSIS
    revision: c3319a16588d05036a9e08cf59a92634a5a0e5dd
    groups:
    - core
    - ble_nxp
    userdata:
      track_branch: mcux_main
  - name: mcux-soc-svd
    path: mcuxsdk/svd
    revision: main
    groups:
    - optional
    userdata:
      track_branch: main
  - name: mcu-sdk-examples
    revision: 7aaade41bcc5dacec7bfb1a59de71b28da9bf157
    repo-path: mcuxsdk-examples
    path: mcuxsdk/examples
    groups:
    - examples
    - ble_nxp
    userdata:
      track_branch: main
  - name: mcu-sdk-components
    repo-path: mcux-component
    revision: 8895c65a3811779b6335ae8ffeffce8a774d30c8
    path: mcuxsdk/components
    groups:
    - components
    - ble_nxp
    userdata:
      track_branch: mcux_main
  - name: mcu-sdk-doc
    repo-path: mcuxsdk-doc
    revision: 33dd831bc7148959e9e32484667c8caada56dcc2
    path: mcuxsdk/docs
    west-commands: scripts/west_commands.yml
    groups:
    - doc
    userdata:
      track_branch: main
  - name: mcuxsdk-tool-data
    revision: d4e6ad4f43a6b260fb26a1e56c469891a63c01a9
    path: mcuxsdk/tool_data
    groups:
    - core
    userdata:
      track_branch: main
