manifest:
  remotes:
  - name: nxp
    url-base: https://github.com/NXP
  - name: nxp-zephyr
    url-base: https://github.com/nxp-zephyr
  - name: nxp-mcuxpresso
    url-base: https://github.com/nxp-mcuxpresso
  defaults:
    remote: nxp-mcuxpresso
  projects:
  - name: bifrost
    path: bifrost
    remote: nxp-zephyr
    revision: 8d6111da5d542406ab179534e055bfa8455ceb70
    west-commands: scripts/west_commands.yml
    groups:
    - bifrost
    userdata:
      track_branch: main
      branch_flow: false
  - name: core
    path: mcuxsdk/
    repo-path: mcuxsdk-core
    revision: 7eb9e7355d09c67fbb34c736df28bcf78795c1e6
    west-commands: scripts/west_commands.yml
    groups:
    - core
    - ble_nxp
    userdata:
      track_branch: main
      branch_flow: true
      display_name: Peripheral Driver
      description: Drivers for common use cases of hardware peripherals, simplifying
        access and integration.
  - name: CMSIS
    repo-path: mcu-sdk-cmsis
    path: mcuxsdk/arch/arm/CMSIS
    revision: e07cca54712c65a938f41a3e72fbfcb20e2f864a
    groups:
    - core
    - ble_nxp
    userdata:
      track_branch: mcux_main
      branch_flow: false
      display_name: CMSIS
      description: Vendor-independent hardware abstraction layer for microcontrollers
        that are based on Arm Cortex processors, distributed by ARM.
  - name: mcux-soc-svd
    path: mcuxsdk/svd
    revision: c80cd50ad08f9d85343c63d4f861c516d5ca2312
    groups:
    - optional
    userdata:
      track_branch: main
      branch_flow: false
      display_name: Device SVD
      description: System View Description (SVD) files for NXP MCU devices, providing
        detailed peripheral register definitions
  - name: mcu-sdk-examples
    revision: 0ec1c2d8f28d927ed1d63e6c4087fb05141ca28b
    repo-path: mcuxsdk-examples
    path: mcuxsdk/examples
    groups:
    - examples
    - ble_nxp
    userdata:
      track_branch: main
      branch_flow: true
      display_name: Out-of-box Examples
      description: Out-of-box examples demonstrating peripheral driver usage and middleware
        integration.
  - name: mcu-sdk-components
    repo-path: mcux-component
    revision: 7bdc048daf5d4541cc2e65da10b60fd015e50725
    path: mcuxsdk/components
    groups:
    - components
    - ble_nxp
    userdata:
      track_branch: mcux_main
      branch_flow: true
      display_name: Components and Board Peripheral Drivers
      description: NXP MCU SDK components and board-specific peripheral driver libraries
  - name: mcu-sdk-doc
    repo-path: mcuxsdk-doc
    revision: 15d622a1bb4d2847228b3f4258197d72ebc97235
    path: mcuxsdk/docs
    west-commands: scripts/west_commands.yml
    groups:
    - doc
    userdata:
      track_branch: main
      branch_flow: false
      display_name: Documentation
      description: Documentation for NXP MCUXpresso SDK, providing comprehensive reference
        materials
  - name: mcuxsdk-tool-data
    revision: 8c04fb313c31b3eeeef719e103e0ad9950d5c29d
    path: mcuxsdk/tool_data
    groups:
    - core
    userdata:
      track_branch: main
      branch_flow: false
      display_name: SDK Tool Data
      description: Additional tooling and configuration data for NXP MCU SDK development
        environment
