manifest:
  remotes:
  - name: nxp
    url-base: https://github.com/NXP
  - name: nxp-zephyr
    url-base: https://github.com/nxp-zephyr
  - name: nxp-mcuxpresso
    url-base: https://github.com/nxp-mcuxpresso
  defaults:
    remote: nxp-mcuxpresso
  projects:
  - name: bifrost
    path: bifrost
    remote: nxp-zephyr
    revision: 89a755bfd0d6efa018ec381b22d5f59e1e4e8043
    west-commands: scripts/west_commands.yml
    groups:
    - bifrost
    userdata:
      track_branch: main
      branch_flow: false
  - name: core
    path: mcuxsdk/
    repo-path: mcuxsdk-core
    revision: e72de975a97b0948b512b39c4e45c04c5b57130e
    west-commands: scripts/west_commands.yml
    groups:
    - core
    - ble_nxp
    userdata:
      track_branch: main
      branch_flow: true
      display_name: Peripheral Driver
      description: Drivers for common use cases of hardware peripherals, simplifying
        access and integration.
  - name: CMSIS
    repo-path: mcu-sdk-cmsis
    path: mcuxsdk/arch/arm/CMSIS
    revision: dc8b75b360fce9c864a12f1ccc54172e0c733805
    groups:
    - core
    - ble_nxp
    userdata:
      track_branch: mcux_main
      branch_flow: false
      display_name: CMSIS
      description: Vendor-independent hardware abstraction layer for microcontrollers
        that are based on Arm Cortex processors, distributed by ARM.
  - name: mcux-soc-svd
    path: mcuxsdk/svd
    revision: ce716920d63552ae26dae30e31634e094dd405be
    groups:
    - optional
    userdata:
      track_branch: main
      branch_flow: false
      display_name: Device SVD
      description: System View Description (SVD) files for NXP MCU devices, providing
        detailed peripheral register definitions
  - name: mcu-sdk-examples
    revision: 0ab35717f277207c107f4465ce67e2491347aa73
    repo-path: mcuxsdk-examples
    path: mcuxsdk/examples
    groups:
    - examples
    - ble_nxp
    userdata:
      track_branch: main
      branch_flow: true
      display_name: Out-of-box Examples
      description: Out-of-box examples demonstrating peripheral driver usage and middleware
        integration.
  - name: mcu-sdk-components
    repo-path: mcux-component
    revision: db88aece6e86253ce96d8fcc1c87271ce199ce06
    path: mcuxsdk/components
    groups:
    - components
    - ble_nxp
    userdata:
      track_branch: mcux_main
      branch_flow: true
      display_name: Components and Board Peripheral Drivers
      description: NXP MCU SDK components and board-specific peripheral driver libraries
  - name: mcu-sdk-doc
    repo-path: mcuxsdk-doc
    revision: da45f0a2185a1b8b97d6fe98eb6e3bc39d0621c4
    path: mcuxsdk/docs
    west-commands: scripts/west_commands.yml
    groups:
    - doc
    userdata:
      track_branch: main
      branch_flow: false
      display_name: Documentation
      description: Documentation for NXP MCUXpresso SDK, providing comprehensive reference
        materials
  - name: mcuxsdk-tool-data
    revision: 53d57aa49c318d971937bfd605f822a1a06d1a86
    path: mcuxsdk/tool_data
    groups:
    - core
    userdata:
      track_branch: main
      branch_flow: false
      display_name: SDK Tool Data
      description: Additional tooling and configuration data for NXP MCU SDK development
        environment
