manifest:
  remotes:
  - name: nxp
    url-base: https://github.com/NXP
  - name: nxp-zephyr
    url-base: https://github.com/nxp-zephyr
  - name: nxp-mcuxpresso
    url-base: https://github.com/nxp-mcuxpresso
  defaults:
    remote: nxp-mcuxpresso
  projects:
  - name: bifrost
    path: bifrost
    remote: nxp-zephyr
    revision: 4b12fdd35e36b2d24ec5d8a859b90185fb3b6ce1
    west-commands: scripts/west_commands.yml
    groups:
    - bifrost
    userdata:
      track_branch: main
      branch_flow: false
  - name: core
    path: mcuxsdk/
    repo-path: mcuxsdk-core
    revision: db9e34d261c0f9ef1b930cc5e7062eb3a9b0a9df
    west-commands: scripts/west_commands.yml
    groups:
    - core
    - ble_nxp
    userdata:
      track_branch: main
      branch_flow: true
  - name: CMSIS
    repo-path: mcu-sdk-cmsis
    path: mcuxsdk/arch/arm/CMSIS
    revision: a76ba3495fc5a68c71bc098ec177613b9b28cca5
    groups:
    - core
    - ble_nxp
    userdata:
      track_branch: mcux_main
      branch_flow: false
  - name: mcux-soc-svd
    path: mcuxsdk/svd
    revision: ab50727a6622f2e75e6ef3d7b93ae8b89eb3ef2e
    groups:
    - optional
    userdata:
      track_branch: main
      branch_flow: false
  - name: mcu-sdk-examples
    revision: a6d33dce244b3777d14fb121d9d368c4bddbb00d
    repo-path: mcuxsdk-examples
    path: mcuxsdk/examples
    groups:
    - examples
    - ble_nxp
    userdata:
      track_branch: main
      branch_flow: true
  - name: mcu-sdk-components
    repo-path: mcux-component
    revision: e3af5ce03ed0ca3a791b88fc2fd275bd4f730b28
    path: mcuxsdk/components
    groups:
    - components
    - ble_nxp
    userdata:
      track_branch: mcux_main
      branch_flow: true
  - name: mcu-sdk-doc
    repo-path: mcuxsdk-doc
    revision: 44fb635cad0d0b92ae03b20e94152715ff0bb07a
    path: mcuxsdk/docs
    west-commands: scripts/west_commands.yml
    groups:
    - doc
    userdata:
      track_branch: main
      branch_flow: false
  - name: mcuxsdk-tool-data
    revision: f5e06eada7dd4aa53627c5343c3c8a81bf3ecc51
    path: mcuxsdk/tool_data
    groups:
    - core
    userdata:
      track_branch: main
      branch_flow: false
