manifest:
  remotes:
  - name: nxp
    url-base: https://github.com/NXP
  - name: nxp-zephyr
    url-base: https://github.com/nxp-zephyr
  - name: nxp-mcuxpresso
    url-base: https://github.com/nxp-mcuxpresso
  defaults:
    remote: nxp-mcuxpresso
  projects:
  - name: bifrost
    path: bifrost
    remote: nxp-zephyr
    revision: 08d2a0a3f72d9ce9f63779f37d1b6d60ee2c4ec3
    west-commands: scripts/west_commands.yml
    groups:
    - bifrost
    userdata:
      track_branch: main
      branch_flow: false
  - name: core
    path: mcuxsdk/
    repo-path: mcuxsdk-core
    revision: a436fa9a6a4fc7fb2f86f379ddc5e9c991feac0e
    west-commands: scripts/west_commands.yml
    groups:
    - core
    - ble_nxp
    userdata:
      track_branch: main
      branch_flow: true
  - name: CMSIS
    repo-path: mcu-sdk-cmsis
    path: mcuxsdk/arch/arm/CMSIS
    revision: 360049cdcff5aad83c31fc67112255edbf5ccc6b
    groups:
    - core
    - ble_nxp
    userdata:
      track_branch: mcux_main
      branch_flow: false
  - name: mcux-soc-svd
    path: mcuxsdk/svd
    revision: d7b7928d4fdeb71a6497fb4503ff8ba370ab776e
    groups:
    - optional
    userdata:
      track_branch: main
      branch_flow: false
  - name: mcu-sdk-examples
    revision: 30c93c22201b8c148d7b59179b1b51232f9a50b1
    repo-path: mcuxsdk-examples
    path: mcuxsdk/examples
    groups:
    - examples
    - ble_nxp
    userdata:
      track_branch: main
      branch_flow: true
  - name: mcu-sdk-components
    repo-path: mcux-component
    revision: 0f5831edbb30785ca2d6d191cb916feecd1b4f91
    path: mcuxsdk/components
    groups:
    - components
    - ble_nxp
    userdata:
      track_branch: mcux_main
      branch_flow: true
  - name: mcu-sdk-doc
    repo-path: mcuxsdk-doc
    revision: 5bd49d7a018416cd811d01505d3d962ab57a8fcc
    path: mcuxsdk/docs
    west-commands: scripts/west_commands.yml
    groups:
    - doc
    userdata:
      track_branch: main
      branch_flow: false
  - name: mcuxsdk-tool-data
    revision: f5e06eada7dd4aa53627c5343c3c8a81bf3ecc51
    path: mcuxsdk/tool_data
    groups:
    - core
    userdata:
      track_branch: main
      branch_flow: false
