manifest:
  remotes:
  - name: nxp
    url-base: https://github.com/NXP
  - name: nxp-zephyr
    url-base: https://github.com/nxp-zephyr
  - name: nxp-mcuxpresso
    url-base: https://github.com/nxp-mcuxpresso
  defaults:
    remote: nxp-mcuxpresso
  projects:
  - name: bifrost
    path: bifrost
    remote: nxp-zephyr
    revision: 9d7384cbecd58e98a32db5033d1d212202fe00d9
    west-commands: scripts/west_commands.yml
    groups:
    - bifrost
    userdata:
      track_branch: main
  - name: core
    path: mcuxsdk/
    repo-path: mcuxsdk-core
    revision: 0f32e85832d34da8724a9d366b99fec22c3fdf38
    west-commands: scripts/west_commands.yml
    groups:
    - core
    userdata:
      track_branch: release/24.12.00
  - name: CMSIS
    repo-path: mcu-sdk-cmsis
    path: mcuxsdk/arch/arm/CMSIS
    revision: c3319a16588d05036a9e08cf59a92634a5a0e5dd
    groups:
    - core
    userdata:
      track_branch: release/24.12.00
  - name: mcux-soc-svd
    path: mcuxsdk/svd
    revision: main
    groups:
    - optional
    userdata:
      track_branch: main
  - name: mcu-sdk-examples
    revision: d9ac6daaba0c102ae29e12df5698c1def9e4b439
    repo-path: mcuxsdk-examples
    path: mcuxsdk/examples
    groups:
    - examples
    userdata:
      track_branch: release/24.12.00
  - name: mcu-sdk-components
    repo-path: mcux-component
    revision: 361f4146ae2a4f4d851a1498a7b08a48bcb8beeb
    path: mcuxsdk/components
    groups:
    - components
    userdata:
      track_branch: release/24.12.00
  - name: mcu-sdk-doc
    repo-path: mcuxsdk-doc
    revision: e0abce43fbba4f779b256eb00be16c74fb6250e7
    path: mcuxsdk/docs
    west-commands: scripts/west_commands.yml
    groups:
    - doc
    userdata:
      track_branch: release/24.12.00
  - name: mcuxsdk-tool-data
    revision: 847bb0d79805065d45b5e6aa57e3d8d7a0ac7d48
    path: mcuxsdk/tool_data
    groups:
    - core
    userdata:
      track_branch: release/24.12.00
