manifest:
  remotes:
  - name: nxp
    url-base: https://github.com/NXP
  - name: nxp-zephyr
    url-base: https://github.com/nxp-zephyr
  - name: nxp-mcuxpresso
    url-base: https://github.com/nxp-mcuxpresso
  defaults:
    remote: nxp-mcuxpresso
  projects:
  - name: bifrost
    path: bifrost
    remote: nxp-zephyr
    revision: 4b12fdd35e36b2d24ec5d8a859b90185fb3b6ce1
    west-commands: scripts/west_commands.yml
    groups:
    - bifrost
    userdata:
      track_branch: main
      branch_flow: false
  - name: core
    path: mcuxsdk/
    repo-path: mcuxsdk-core
    revision: 2893c6df8c59f5763476300b584907c4d59ff2e2
    west-commands: scripts/west_commands.yml
    groups:
    - core
    - ble_nxp
    userdata:
      track_branch: release/25.06.00
      branch_flow: true
  - name: CMSIS
    repo-path: mcu-sdk-cmsis
    path: mcuxsdk/arch/arm/CMSIS
    revision: a76ba3495fc5a68c71bc098ec177613b9b28cca5
    groups:
    - core
    - ble_nxp
    userdata:
      track_branch: mcux_main
      branch_flow: false
  - name: mcux-soc-svd
    path: mcuxsdk/svd
    revision: da354fa1807150dcbe1e9bddbd92ab9b11fc6454
    groups:
    - optional
    userdata:
      track_branch: main
      branch_flow: false
  - name: mcu-sdk-examples
    revision: ca1e57cf33345e70de398a82bccedfcfae2a270f
    repo-path: mcuxsdk-examples
    path: mcuxsdk/examples
    groups:
    - examples
    - ble_nxp
    userdata:
      track_branch: release/25.06.00
      branch_flow: true
  - name: mcu-sdk-components
    repo-path: mcux-component
    revision: 2a884681d3fd3c8d13ea54204208b31513a36c03
    path: mcuxsdk/components
    groups:
    - components
    - ble_nxp
    userdata:
      track_branch: release/25.06.00
      branch_flow: true
  - name: mcu-sdk-doc
    repo-path: mcuxsdk-doc
    revision: 98006ab0d9a201fefdccbbe6fafb83fb1a5751da
    path: mcuxsdk/docs
    west-commands: scripts/west_commands.yml
    groups:
    - doc
    userdata:
      track_branch: main
      branch_flow: false
  - name: mcuxsdk-tool-data
    revision: f5e06eada7dd4aa53627c5343c3c8a81bf3ecc51
    path: mcuxsdk/tool_data
    groups:
    - core
    userdata:
      track_branch: main
      branch_flow: false
