manifest:
  remotes:
  - name: nxp
    url-base: https://github.com/NXP
  - name: nxp-zephyr
    url-base: https://github.com/nxp-zephyr
  - name: nxp-mcuxpresso
    url-base: https://github.com/nxp-mcuxpresso
  defaults:
    remote: nxp-mcuxpresso
  projects:
  - name: bifrost
    path: bifrost
    remote: nxp-zephyr
    revision: 9d7384cbecd58e98a32db5033d1d212202fe00d9
    west-commands: scripts/west_commands.yml
    groups:
    - bifrost
    userdata:
      track_branch: main
  - name: core
    path: mcuxsdk/
    repo-path: mcuxsdk-core
    revision: c06b5acf22c56e8999654f79d58608a71e99a63c
    west-commands: scripts/west_commands.yml
    groups:
    - core
    userdata:
      track_branch: release/24.12.00
  - name: CMSIS
    repo-path: mcu-sdk-cmsis
    path: mcuxsdk/arch/arm/CMSIS
    revision: c3319a16588d05036a9e08cf59a92634a5a0e5dd
    groups:
    - core
    userdata:
      track_branch: release/24.12.00
  - name: mcux-soc-svd
    path: mcuxsdk/svd
    revision: main
    groups:
    - optional
    userdata:
      track_branch: main
  - name: mcu-sdk-examples
    revision: c4f125e96ec302771dc74fc2f5aaa011b354919a
    repo-path: mcuxsdk-examples
    path: mcuxsdk/examples
    groups:
    - examples
    userdata:
      track_branch: release/24.12.00
  - name: mcu-sdk-components
    repo-path: mcux-component
    revision: 0a95c0536c168a97e1caac0bc41898c3cf9f75a8
    path: mcuxsdk/components
    groups:
    - components
    userdata:
      track_branch: release/24.12.00
  - name: mcu-sdk-doc
    repo-path: mcuxsdk-doc
    revision: bdcf890becf96be4e30be78d22dbc1f848c07b80
    path: mcuxsdk/docs
    west-commands: scripts/west_commands.yml
    groups:
    - doc
    userdata:
      track_branch: release/24.12.00
  - name: mcuxsdk-tool-data
    revision: 847bb0d79805065d45b5e6aa57e3d8d7a0ac7d48
    path: mcuxsdk/tool_data
    groups:
    - core
    userdata:
      track_branch: release/24.12.00
