manifest:
  remotes:
  - name: nxp
    url-base: https://github.com/NXP
  - name: nxp-zephyr
    url-base: https://github.com/nxp-zephyr
  - name: nxp-mcuxpresso
    url-base: https://github.com/nxp-mcuxpresso
  defaults:
    remote: nxp-mcuxpresso
  projects:
  - name: bifrost
    path: bifrost
    remote: nxp-zephyr
    revision: 8fc70942acfd950372052fc86ed82c0b0e983446
    west-commands: scripts/west_commands.yml
    groups:
    - bifrost
    userdata:
      track_branch: main
      branch_flow: false
  - name: core
    path: mcuxsdk/
    repo-path: mcuxsdk-core
    revision: af754bcc58cfde9d05168942e5564d018e566aff
    west-commands: scripts/west_commands.yml
    groups:
    - core
    - ble_nxp
    userdata:
      track_branch: main
      branch_flow: true
      display_name: Peripheral Driver
      description: Drivers for common use cases of hardware peripherals, simplifying
        access and integration.
  - name: CMSIS
    repo-path: mcu-sdk-cmsis
    path: mcuxsdk/arch/arm/CMSIS
    revision: e07cca54712c65a938f41a3e72fbfcb20e2f864a
    groups:
    - core
    - ble_nxp
    userdata:
      track_branch: mcux_main
      branch_flow: false
      display_name: CMSIS
      description: Vendor-independent hardware abstraction layer for microcontrollers
        that are based on Arm Cortex processors, distributed by ARM.
  - name: mcux-soc-svd
    path: mcuxsdk/svd
    revision: 0edfb6c41652ea0b0513b87b0855c0c621d35c17
    groups:
    - optional
    userdata:
      track_branch: main
      branch_flow: false
      display_name: Device SVD
      description: System View Description (SVD) files for NXP MCU devices, providing
        detailed peripheral register definitions
  - name: mcu-sdk-examples
    revision: d26e706519ab2c2f2f03cc5ad54cbba6dadaee31
    repo-path: mcuxsdk-examples
    path: mcuxsdk/examples
    groups:
    - examples
    - ble_nxp
    userdata:
      track_branch: main
      branch_flow: true
      display_name: Out-of-box Examples
      description: Out-of-box examples demonstrating peripheral driver usage and middleware
        integration.
  - name: mcu-sdk-components
    repo-path: mcux-component
    revision: 5f841d86378a1d085c1f4258e9ffbf8b98998036
    path: mcuxsdk/components
    groups:
    - components
    - ble_nxp
    userdata:
      track_branch: mcux_main
      branch_flow: true
      display_name: Components and Board Peripheral Drivers
      description: NXP MCU SDK components and board-specific peripheral driver libraries
  - name: mcu-sdk-doc
    repo-path: mcuxsdk-doc
    revision: 1ff5263230b57637a753c3bded991d0e6e18101d
    path: mcuxsdk/docs
    west-commands: scripts/west_commands.yml
    groups:
    - doc
    userdata:
      track_branch: main
      branch_flow: false
      display_name: Documentation
      description: Documentation for NXP MCUXpresso SDK, providing comprehensive reference
        materials
  - name: mcuxsdk-tool-data
    revision: 735a78992f507b033d4bab47ac81eda32479d92f
    path: mcuxsdk/tool_data
    groups:
    - core
    userdata:
      track_branch: main
      branch_flow: false
      display_name: SDK Tool Data
      description: Additional tooling and configuration data for NXP MCU SDK development
        environment
