manifest:
  remotes:
  - name: nxp
    url-base: https://github.com/NXP
  - name: nxp-zephyr
    url-base: https://github.com/nxp-zephyr
  - name: nxp-mcuxpresso
    url-base: https://github.com/nxp-mcuxpresso
  defaults:
    remote: nxp-mcuxpresso
  projects:
  - name: bifrost
    path: bifrost
    remote: nxp-zephyr
    revision: main
    west-commands: scripts/west_commands.yml
    groups:
    - bifrost
    userdata:
      track_branch: main
  - name: core
    path: mcuxsdk/
    repo-path: mcuxsdk-core
    revision: b45609db10be98aa19d61a6b81f46eb68bb734de
    west-commands: scripts/west_commands.yml
    groups:
    - core
    - ble_nxp
    userdata:
      track_branch: main
  - name: CMSIS
    repo-path: mcu-sdk-cmsis
    path: mcuxsdk/arch/arm/CMSIS
    revision: 8cb83f495fcac259b628e44dfac343d6a83e832d
    groups:
    - core
    - ble_nxp
    userdata:
      track_branch: mcux_main
  - name: mcux-soc-svd
    path: mcuxsdk/svd
    revision: 879f26d03799d7e964d1ee97d4f65b88aa92de35
    groups:
    - optional
    userdata:
      track_branch: main
  - name: mcu-sdk-examples
    revision: b8ef9f599a85b9b00f6af44231f8439b6b6e95b6
    repo-path: mcuxsdk-examples
    path: mcuxsdk/examples
    groups:
    - examples
    - ble_nxp
    userdata:
      track_branch: main
  - name: mcu-sdk-components
    repo-path: mcux-component
    revision: bfb3ada11d0918793082507f514d56e6633638a3
    path: mcuxsdk/components
    groups:
    - components
    - ble_nxp
    userdata:
      track_branch: mcux_main
  - name: mcu-sdk-doc
    repo-path: mcuxsdk-doc
    revision: 136461a6035e103c70633ad347d045bb4f491b3a
    path: mcuxsdk/docs
    west-commands: scripts/west_commands.yml
    groups:
    - doc
    userdata:
      track_branch: main
  - name: mcuxsdk-tool-data
    revision: 2a004b67544517976ecded8a5d5e8c9e3886bae7
    path: mcuxsdk/tool_data
    groups:
    - core
    userdata:
      track_branch: main
