manifest:
  remotes:
  - name: nxp
    url-base: https://github.com/NXP
  - name: nxp-zephyr
    url-base: https://github.com/nxp-zephyr
  - name: nxp-mcuxpresso
    url-base: https://github.com/nxp-mcuxpresso
  defaults:
    remote: nxp-mcuxpresso
  projects:
  - name: bifrost
    path: bifrost
    remote: nxp-zephyr
    revision: main
    west-commands: scripts/west_commands.yml
    groups:
    - bifrost
    userdata:
      track_branch: main
  - name: core
    path: mcuxsdk/
    repo-path: mcuxsdk-core
    revision: 8d9f4b26e4c1f94193134850d1a7060716bb3848
    west-commands: scripts/west_commands.yml
    groups:
    - core
    - ble_nxp
    userdata:
      track_branch: main
  - name: CMSIS
    repo-path: mcu-sdk-cmsis
    path: mcuxsdk/arch/arm/CMSIS
    revision: 8cb83f495fcac259b628e44dfac343d6a83e832d
    groups:
    - core
    - ble_nxp
    userdata:
      track_branch: mcux_main
  - name: mcux-soc-svd
    path: mcuxsdk/svd
    revision: main
    groups:
    - optional
    userdata:
      track_branch: main
  - name: mcu-sdk-examples
    revision: b98e1addb06323333c86c940a3dbd7bef6ed6564
    repo-path: mcuxsdk-examples
    path: mcuxsdk/examples
    groups:
    - examples
    - ble_nxp
    userdata:
      track_branch: main
  - name: mcu-sdk-components
    repo-path: mcux-component
    revision: 3d6ce869f76bd61cff475d0e1294abdaa86eb2d2
    path: mcuxsdk/components
    groups:
    - components
    - ble_nxp
    userdata:
      track_branch: mcux_main
  - name: mcu-sdk-doc
    repo-path: mcuxsdk-doc
    revision: b50d2346795a5e14643b77acebf87c9c0a13f75f
    path: mcuxsdk/docs
    west-commands: scripts/west_commands.yml
    groups:
    - doc
    userdata:
      track_branch: main
  - name: mcuxsdk-tool-data
    revision: 2a004b67544517976ecded8a5d5e8c9e3886bae7
    path: mcuxsdk/tool_data
    groups:
    - core
    userdata:
      track_branch: main
