manifest:
  remotes:
  - name: nxp
    url-base: https://github.com/NXP
  - name: nxp-zephyr
    url-base: https://github.com/nxp-zephyr
  - name: nxp-mcuxpresso
    url-base: https://github.com/nxp-mcuxpresso
  defaults:
    remote: nxp-mcuxpresso
  projects:
  - name: bifrost
    path: bifrost
    remote: nxp-zephyr
    revision: e1abadfb8f739079268e94344200d635e737e972
    west-commands: scripts/west_commands.yml
    groups:
    - bifrost
    userdata:
      track_branch: main
      branch_flow: false
  - name: core
    path: mcuxsdk/
    repo-path: mcuxsdk-core
    revision: 2b40cdd467669c20b8ad5e34576c063275b609e5
    west-commands: scripts/west_commands.yml
    groups:
    - core
    - ble_nxp
    userdata:
      track_branch: main
      branch_flow: true
  - name: CMSIS
    repo-path: mcu-sdk-cmsis
    path: mcuxsdk/arch/arm/CMSIS
    revision: 360049cdcff5aad83c31fc67112255edbf5ccc6b
    groups:
    - core
    - ble_nxp
    userdata:
      track_branch: mcux_main
      branch_flow: false
  - name: mcux-soc-svd
    path: mcuxsdk/svd
    revision: ef1ae91455885ae5aec16d73f518b5e9eed4ef3b
    groups:
    - optional
    userdata:
      track_branch: main
      branch_flow: false
  - name: mcu-sdk-examples
    revision: 4d780c703fd4e5b2d5c4c1ef0779a14a897360bf
    repo-path: mcuxsdk-examples
    path: mcuxsdk/examples
    groups:
    - examples
    - ble_nxp
    userdata:
      track_branch: main
      branch_flow: true
  - name: mcu-sdk-components
    repo-path: mcux-component
    revision: bbc8406387d49c02632d5c9bebfca14896048ec9
    path: mcuxsdk/components
    groups:
    - components
    - ble_nxp
    userdata:
      track_branch: mcux_main
      branch_flow: true
  - name: mcu-sdk-doc
    repo-path: mcuxsdk-doc
    revision: e215e03b46863a9f4973ca2401964eb7af69b98f
    path: mcuxsdk/docs
    west-commands: scripts/west_commands.yml
    groups:
    - doc
    userdata:
      track_branch: main
      branch_flow: false
  - name: mcuxsdk-tool-data
    revision: f5e06eada7dd4aa53627c5343c3c8a81bf3ecc51
    path: mcuxsdk/tool_data
    groups:
    - core
    userdata:
      track_branch: main
      branch_flow: false
