manifest:
  remotes:
  - name: nxp
    url-base: https://github.com/NXP
  - name: nxp-zephyr
    url-base: https://github.com/nxp-zephyr
  - name: nxp-mcuxpresso
    url-base: https://github.com/nxp-mcuxpresso
  defaults:
    remote: nxp-mcuxpresso
  projects:
  - name: bifrost
    path: bifrost
    remote: nxp-zephyr
    revision: main
    west-commands: scripts/west_commands.yml
    groups:
    - bifrost
    userdata:
      track_branch: main
  - name: core
    path: mcuxsdk/
    repo-path: mcuxsdk-core
    revision: 5af81e4b9257d180bf21c11d4fb5a87b70f8d20f
    west-commands: scripts/west_commands.yml
    groups:
    - core
    - ble_nxp
    userdata:
      track_branch: main
  - name: CMSIS
    repo-path: mcu-sdk-cmsis
    path: mcuxsdk/arch/arm/CMSIS
    revision: c3319a16588d05036a9e08cf59a92634a5a0e5dd
    groups:
    - core
    - ble_nxp
    userdata:
      track_branch: mcux_main
  - name: mcux-soc-svd
    path: mcuxsdk/svd
    revision: main
    groups:
    - optional
    userdata:
      track_branch: main
  - name: mcu-sdk-examples
    revision: 3900bb9d53201b99909afd7dad40ee677db42199
    repo-path: mcuxsdk-examples
    path: mcuxsdk/examples
    groups:
    - examples
    - ble_nxp
    userdata:
      track_branch: main
  - name: mcu-sdk-components
    repo-path: mcux-component
    revision: fdba1a82ec5014de7b958cbdc8e367865653429b
    path: mcuxsdk/components
    groups:
    - components
    - ble_nxp
    userdata:
      track_branch: mcux_main
  - name: mcu-sdk-doc
    repo-path: mcuxsdk-doc
    revision: 10dbf89be66aa30a4bc009523c87caa1e3796f7e
    path: mcuxsdk/docs
    west-commands: scripts/west_commands.yml
    groups:
    - doc
    userdata:
      track_branch: main
  - name: mcuxsdk-tool-data
    revision: d4e6ad4f43a6b260fb26a1e56c469891a63c01a9
    path: mcuxsdk/tool_data
    groups:
    - core
    userdata:
      track_branch: main
